settings:
    displayErrorDetails: true
    doctrine:
        mapping_path: '/../src/Domain/Entity'
        driver: pdo_mysql
        host: localhost
        dbname: mn_tv_listings
        user: root
        password: ''
        charset: utf8
    view:
        template_path: '/../app/templates'
        twig:
            cache: '/../app/cache/twig'
            debug: true
            auto_reload: true
    video_proxy:
        base_path: 'localhost'

migrations:
    directory: '/../app/migrations/'
    name: 'Tvlistings migrations'
    namespace:  'TVListings\Migrations'
    table_name: 'tvlisting_migrations'
